version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeedb
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./   #  <--- directory, . is at current directory 
      dockerfile: Dockerfile   # at current directory, use Dockerfile 
    ports:        
      - "8080:8080"
    depends_on:   # using this SQL db 
      - mysqldb
    networks:   # use this network   
      springboot-mysql-net:
    restart: on-failure   # when failed, restart the app 

networks:
  springboot-mysql-net:
